export const FETCH_WEATHER = 'FETCH_WEATHER'
export const FETCH_WEATHER_PENDING = 'FETCH_WEATHER_PENDING'
export const FETCH_WEATHER_FULFILLED = 'FETCH_WEATHER_FULFILLED'
export const FETCH_WEATHER_REJECTED = 'FETCH_WEATHER_REJECTED'

export const FETCH_NEWS = 'FETCH_NEWS'
export const FETCH_NEWS_PENDING = 'FETCH_NEWS_PENDING'
export const FETCH_NEWS_FULFILLED = 'FETCH_NEWS_FULFILLED'
export const FETCH_NEWS_REJECTED = 'FETCH_NEWS_REJECTED'
